xrpc:
  port: 8089
  applicationName: a-n
  registryConfig:
    connect: zookeeper://127.0.0.1:2181
  serializeType: jdk
  compressType: gzip
  loadBalanceType: consistentHash
  idGenerator:
    class: com.meiya.utils.IdGenerator
    dataCenterId: 4
    machineId: 9